# Generated by Django 2.0.6 on 2019-02-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(max_length=4)),
                ('mpg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
